FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN DATABASE_URL=file:dummy.db npm run build
# ENV DATABASE_URL=file:local.db
# RUN DATABASE_URL=file:dummy.db npm run build
# RUN npm run build
# RUN npm prune --production

FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/build build/
COPY --from=builder /app/node_modules node_modules/
COPY package.json .

# Copy migration files (generated by db:generate)
COPY drizzle drizzle/

# Copy config so migrate knows where to find migrations
COPY drizzle.config.js ./

COPY src/lib/server/db/schema.js src/lib/server/db/schema.js

EXPOSE 3000
ENV NODE_ENV=production
CMD ["sh", "-c", "npm run db:migrate && node build"]
# CMD [ "node", "build" ]
# CMD npx drizzle-kit migrate --config=drizzle.config.js && node build

